networks:
    backend:
services:
  customerdb:
    container_name: customer-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd  
    networks: 
      - backend
    ports:
       - 18001:1433

  customerwebapi:
    container_name: customer-api
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: CustomerWebApi/Dockerfile
    networks:
      - backend
    ports:
       - 18002:80
    environment:
        - DB_HOST=customerdb
        - DB_NAME=dms_customer
        - DB_SA_PASSWORD=Passw0rd

  productdb:
    container_name: product-db
    image: mysql:8.0.29-oracle
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd
    ports:
       - 18003:3306
    networks:
     - backend    

  productwebapi:
    container_name: product-api
    image: ${DOCKER_REGISTRY-}productwebapi
    build:
      context: .
      dockerfile: ProductWebApi/Dockerfile
    networks:
      - backend
    ports:
       - 8004:80
    environment:
            - DB_HOST=productdb
            - DB_NAME=dms_product
            - DB_SA_PASSWORD=Passw0rd

  orderdb:
    container_name: order-db
    image: mongo
    ports:
      - 18005:27017
    networks:
      - backend 

  orderwebapi:
    container_name: order-api
    image: ${DOCKER_REGISTRY-}orderwebapi
    build:
      context: .
      dockerfile: OrderWebApi/Dockerfile
    ports: 
      - 18006:80
    networks :
      - backend 
    environment:
      - DB_HOST=orderdb
      - DB_NAME=dms_order

